# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages
warnings_are_errors: true
addons:
  apt:
    packages:
      - libnetcdf-dev
      - netcdf-bin
      - libudunits2-dev

after_success:
  - Rscript -e 'covr::codecov()'
