# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages
warnings_are_errors: false
addons:
  apt:
    packages:
      - libnetcdf-dev
      - netcdf-bin
      - libudunits2-dev

after_success:
  - Rscript -e 'covr::codecov()'
  - Rscript -e 'devtools::install_github("eliocamp/metR")'
  - Rscript -e 'pkgdown::build_site()'

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_PAT
  keep-history: true
  local-dir: docs
  on:
    branch: master
